'use client';
import {useEffect,useRef,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './ui/tabs';
import {ToggleGroup,ToggleGroupItem} from './ui/toggle-group';
import {buildShowroom} from './showroom-scene';
const wa='https://wa.me/5511932992410?text=Ol%C3%A1%21%20Gostaria%20de%20um%20or%C3%A7amento.';
const rooms=[{name:'Cozinha',kicker:'01 — ENCONTROS & SABORES',title:<>Seu sonho.<br/>Em cada <em>detalhe.</em></>,text:'Mármore, luz e madeira. Explore as possibilidades de uma cozinha feita para viver.',camera:[5,3.1,6.7],target:[0,1.5,-.4]}, {name:'Lavabo',kicker:'02 — UM MOMENTO SÓ SEU',title:<>A beleza<br/>de <em>desacelerar.</em></>,text:'Superfícies que acolhem. Acabamentos que transformam o seu ritual diário.',camera:[17,2.7,4.7],target:[14,1.9,-1.7]}, {name:'Materiais',kicker:'03 — ESCULPIDO PELA NATUREZA',title:<>A matéria<br/>dos seus <em>sonhos.</em></>,text:'Veios, tons e texturas. Conheça as possibilidades e escolha sua pedra com nossa equipe.',camera:[31,2.7,5.6],target:[28,1.7,-1.4]}, {name:'Projetos',kicker:'04 — DO PROJETO À REALIDADE',title:<>Feito por nós.<br/>Vivido por <em>você.</em></>,text:'Trabalhos reais da Reis Oliveira, apresentados em uma galeria virtual.',camera:[45,2.6,5.8],target:[42,2,-2]}, {name:'Contato',kicker:'05 — MARMORARIA REIS OLIVEIRA',title:<>Vamos criar<br/>o seu <em>ambiente?</em></>,text:'Há mais de cinco anos, seu sonho moldado em pedra. Mauá, Grande ABC, Grande São Paulo e interior.',camera:[4,2.8,7],target:[0,1.4,0]}];
export default function ImmersiveShowroom(){const host=useRef(null),engine=useRef(null);const [room,setRoom]=useState(0),[material,setMaterial]=useState('marble'),[state,setState]=useState('loading');
 useEffect(()=>{let dead=false,clean=()=>{}; (async()=>{try{const T=await import('three');const {RoomEnvironment}=await import('three/addons/environments/RoomEnvironment.js');if(dead)return;const el=host.current,renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;el.appendChild(renderer.domElement);const scene=new T.Scene();scene.background=new T.Color(0x132334);scene.fog=new T.Fog(0x132334,18,45);const camera=new T.PerspectiveCamera(47,1,.1,100);const pmrem=new T.PMREMGenerator(renderer),roomEnv=new RoomEnvironment(),env=pmrem.fromScene(roomEnv,.05);roomEnv.dispose();scene.environment=env.texture;scene.environmentIntensity=.55;scene.add(new T.HemisphereLight(0xc8d9eb,0x78674e,1.1));
 const tex=await new T.TextureLoader().loadAsync('/images/marble-albedo.png');if(dead){tex.dispose();renderer.dispose();renderer.domElement.remove();env.dispose();pmrem.dispose();return;}tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();const set=buildShowroom(T,scene,tex);let index=0,angle=0,drag=false,lastX=0,frame=0;const position=new T.Vector3(...rooms[0].camera),look=new T.Vector3(...rooms[0].target),targetPos=position.clone(),targetLook=look.clone();camera.position.copy(position);const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const size=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.fov=camera.aspect<.8?64:47;camera.updateProjectionMatrix();};const ro=new ResizeObserver(size);ro.observe(el);size();let last=0;
 function draw(t){const dt=Math.min((t-last)/1000,.05);last=t;if(!document.hidden){const p=rooms[index].camera;targetPos.set(p[0]+Math.sin(angle)*1.5,p[1],p[2]+(Math.cos(angle)-1)*1.2);targetLook.set(...rooms[index].target);const f=reduced.matches?1:Math.min(1,dt*4);position.lerp(targetPos,f);look.lerp(targetLook,f);camera.position.copy(position);camera.lookAt(look);renderer.render(scene,camera);}frame=requestAnimationFrame(draw);}
 const down=e=>{if(e.button!==0)return;drag=true;lastX=e.clientX;el.setPointerCapture(e.pointerId);};const move=e=>{if(drag){angle=Math.max(-1.2,Math.min(1.2,angle+(e.clientX-lastX)*.004));lastX=e.clientX;}};const up=()=>{drag=false;};const lost=e=>{e.preventDefault();setState('fallback');};el.addEventListener('pointerdown',down);el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);renderer.domElement.addEventListener('webglcontextlost',lost);
 engine.current={go(i){index=i;angle=0;},rotate(a){angle=Math.max(-1.2,Math.min(1.2,angle+a));},material(value){set.stone.map=value==='marble'?tex:null;set.stone.color.set(value==='marble'?0xffffff:0x25292e);set.stone.needsUpdate=true;}};frame=requestAnimationFrame(draw);setState('ready');clean=()=>{cancelAnimationFrame(frame);ro.disconnect();el.removeEventListener('pointerdown',down);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);set.cleanup();tex.dispose();env.dispose();pmrem.dispose();renderer.dispose();renderer.domElement.remove();engine.current=null;};}catch{if(!dead)setState('fallback');}})();return()=>{dead=true;clean();};},[]);
 const change=i=>{setRoom(i);engine.current?.go(i);};
 return <main className="immersive"><div className="world" ref={host} aria-hidden="true" style={{visibility:state==='ready'?'visible':'hidden'}}/>{state!=='ready'&&<div className="world-fallback"/>}<div className="world-shade"/><header className="immersive-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();change(0);}}><img src="/images/logo-reis-oliveira.jpg" width="48" height="48" alt=""/><span>REIS OLIVEIRA<small>MARMORARIA</small></span></a><a className="header-cta" href={wa} target="_blank" rel="noopener noreferrer">Seu projeto começa aqui ↗</a></header><Tabs value={room} onValueChange={change} className="showroom-tabs"><div className="immersive-copy">{rooms.map((r,i)=><TabsContent value={i} key={r.name}><p className="eyebrow">{r.kicker}</p><h1>{r.title}</h1><p className="world-description">{r.text}</p>{i===4?<div className="world-contact"><a className="button" href={wa} target="_blank" rel="noopener noreferrer">Conversar no WhatsApp ↗</a><a href="tel:+5511932992410">(11) 93299-2410</a><address>Estr. Mauá e Adutora Rio Claro, 730B<br/>Jardim Paranavai · Mauá – SP · 09390-500</address><p>Segunda a sexta · 08h–17h<br/>Sábado · 08h–13h</p><a href="https://www.google.com/maps/search/?api=1&query=Marmoraria+Reis+Oliveira+730B+Maua" target="_blank" rel="noopener noreferrer">Traçar rota ↗</a><a href="mailto:marmorariareisoliveira@gmail.com">marmorariareisoliveira@gmail.com</a></div>:<><a className="button" href={wa} target="_blank" rel="noopener noreferrer">Quero um projeto assim ↗</a>{i===3&&<a className="world-instagram" href="https://www.instagram.com/marmorariareisoliveira/" target="_blank" rel="noopener noreferrer">Ver trabalhos no Instagram ↗</a>}</>}</TabsContent>)}</div><div className="immersive-bottom"><div className="scene-label"><span>{state==='loading'?'PREPARANDO OS AMBIENTES…':state==='fallback'?'VISUALIZAÇÃO ILUSTRATIVA':'ARRASTE O AMBIENTE PARA OLHAR AO REDOR'}</span><small>Showroom conceitual · Projetos da galeria: imagens reais</small></div><TabsList className="room-nav" aria-label="Ambientes do showroom">{rooms.map((r,i)=><TabsTrigger key={r.name} value={i}><small>0{i+1}</small>{r.name}</TabsTrigger>)}</TabsList></div></Tabs>{state==='ready'&&<div className="world-tools"><div className="world-angle"><button aria-label="Olhar para a esquerda" onClick={()=>engine.current?.rotate(-.25)}>←</button><span>EXPLORAR</span><button aria-label="Olhar para a direita" onClick={()=>engine.current?.rotate(.25)}>→</button></div>{room<3&&<ToggleGroup value={[material]} onValueChange={v=>{if(v.length){setMaterial(v[0]);engine.current?.material(v[0]);}}} className="stone-options" aria-label="Acabamento ilustrativo"><ToggleGroupItem value="marble"><span className="swatch light"/>Claro</ToggleGroupItem><ToggleGroupItem value="granite"><span className="swatch dark"/>Escuro</ToggleGroupItem></ToggleGroup>}</div>}</main>;
}
