'use client';
import { useEffect, useRef, useState } from 'react';
import { ToggleGroup, ToggleGroupItem } from './ui/toggle-group';
export default function StoneShowcase(){
 const host=useRef(null), api=useRef(null); const [material,setMaterial]=useState('marble'); const [status,setStatus]=useState('loading');
 useEffect(()=>{let disposed=false,cleanup=()=>{};
 (async()=>{try{
 const T=await import('three'); const {RoomEnvironment}=await import('three/addons/environments/RoomEnvironment.js'); if(disposed)return;
 const el=host.current;const renderer=new T.WebGLRenderer({antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;el.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(35,1,.1,50);camera.position.set(5.5,3.6,6.8);camera.lookAt(0,.6,0);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();
 scene.add(new T.HemisphereLight(0xe3edff,0x141c2d,2));const key=new T.DirectionalLight(0xffe2b4,4);key.position.set(2,6,3);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-5;key.shadow.camera.right=5;key.shadow.camera.top=5;key.shadow.camera.bottom=-5;key.shadow.normalBias=.03;scene.add(key);
 const model=new T.Group();scene.add(model);let seed=19;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 function texture(dark){const c=document.createElement('canvas');c.width=c.height=1024;const x=c.getContext('2d');x.fillStyle=dark?'#23272b':'#e5e2da';x.fillRect(0,0,1024,1024);
 for(let i=0;i<45000;i++){const v=random();x.fillStyle=dark?`rgba(180,190,194,${v*.4})`:`rgba(110,106,96,${v*.045})`;const s=dark?random()*3:random()*5;x.fillRect(random()*1024,random()*1024,s,s);}
 if(!dark)for(let i=0;i<24;i++){let y=random()*1300-150;x.beginPath();x.moveTo(-20,y);for(let j=0;j<12;j++){y+=random()*100-35;x.lineTo(j*100,y);}x.strokeStyle=i%3===0?'rgba(132,112,78,.32)':'rgba(86,94,100,.21)';x.lineWidth=random()*2+.5;x.stroke();x.lineWidth=10;x.strokeStyle='rgba(115,112,104,.035)';x.stroke();}
 const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t;}
 const textures=[texture(false),texture(true)];const stone=new T.MeshPhysicalMaterial({map:textures[0],roughness:.25,metalness:.03,clearcoat:.35,clearcoatRoughness:.22});const wood=new T.MeshStandardMaterial({color:0x443024,roughness:.7});const gold=new T.MeshStandardMaterial({color:0xbda15e,metalness:.85,roughness:.25});
 function box(w,h,d,x,y,z,mat){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;model.add(m);return m;}
 box(3.9,.14,1.65,0,1.32,0,stone);box(.14,1.3,1.65,-1.88,.6,0,stone);box(.14,1.3,1.65,1.88,.6,0,stone);box(3.4,1.05,1.37,0,.61,0,wood);for(let i=0;i<38;i++)box(.025,.99,.035,-1.62+i*.087,.61,.702,gold);
 const tray=new T.Mesh(new T.CylinderGeometry(.31,.29,.035,48),gold);tray.position.set(.95,1.415,.12);model.add(tray);
 const vase=new T.Mesh(new T.LatheGeometry([new T.Vector2(.07,0),new T.Vector2(.17,.1),new T.Vector2(.18,.23),new T.Vector2(.09,.35),new T.Vector2(.07,.43)],40),new T.MeshStandardMaterial({color:0xb8ab94,roughness:.65}));vase.position.set(1,1.43,.1);model.add(vase);
 const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.35}));floor.rotation.x=-Math.PI/2;floor.position.y=-.06;floor.receiveShadow=true;scene.add(floor);
 let target=-.35,drag=false,start=0,visible=true,frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let last=0;
 function draw(time){if(disposed)return;const dt=Math.min((time-last)/1000,.05);last=time;if(visible&&!document.hidden){model.rotation.y+=(target-model.rotation.y)*(reduced.matches?1:Math.min(1,dt*7));renderer.render(scene,camera);}frame=requestAnimationFrame(draw);}
 function resize(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.position.set(5.5,3.6,6.8).multiplyScalar(w/h<1?1.2:1);camera.lookAt(0,.6,0);camera.updateProjectionMatrix();}
 const ro=new ResizeObserver(resize);ro.observe(el);resize();const io=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;});io.observe(el);
 function down(e){if(e.button!==0)return;drag=true;start=e.clientX;el.setPointerCapture(e.pointerId);}function move(e){if(drag){target+=(e.clientX-start)*.009;start=e.clientX;}}function up(){drag=false;}function lost(e){e.preventDefault();setStatus('fallback');}
 el.addEventListener('pointerdown',down);el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);renderer.domElement.addEventListener('webglcontextlost',lost);
 api.current={material(v){stone.map=textures[v==='marble'?0:1];stone.roughness=v==='marble'?.25:.36;stone.needsUpdate=true;},rotate(v){target+=v;},reset(){target=-.35;}};api.current.material(material);model.rotation.y=target;setStatus('ready');frame=requestAnimationFrame(draw);
 cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();el.removeEventListener('pointerdown',down);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);renderer.domElement.removeEventListener('webglcontextlost',lost);scene.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});textures.forEach(t=>t.dispose());env.dispose();pmrem.dispose();renderer.dispose();renderer.domElement.remove();api.current=null;};
 }catch{if(!disposed)setStatus('fallback');}})();return()=>{disposed=true;cleanup();};
 },[]);
 return <div className="showcase"><div className="showcase-heading"><span>ATELIÊ DIGITAL</span><span>01 / BANCADA EM CASCATA</span></div><div className="stone-viewport" ref={host} role="img" aria-label={`Bancada tridimensional em ${material==='marble'?'mármore claro':'granito escuro'}. Use os botões abaixo para girar.`} style={{display:status==='fallback'?'none':undefined}}/>{status==='loading'&&<p className="scene-loading" role="status">Preparando seu ambiente…</p>}{status==='fallback'&&<div className="scene-fallback"><img src="/images/cozinha-essenza.png" alt="Inspiração de bancada clara em cozinha contemporânea"/><p>Visualização ilustrativa. O 3D não está disponível neste dispositivo.</p></div>}<div className="showcase-controls" hidden={status!=='ready'}><p className="drag-hint">ARRASTE PARA EXPLORAR EM 3D</p><ToggleGroup className="stone-options" value={[material]} onValueChange={values=>{if(values.length){setMaterial(values[0]);api.current?.material(values[0]);}}} aria-label="Material da bancada"><ToggleGroupItem value="marble"><span className="swatch light"/>Mármore claro</ToggleGroupItem><ToggleGroupItem value="granite"><span className="swatch dark"/>Granito escuro</ToggleGroupItem></ToggleGroup><div className="rotation-controls"><button onClick={()=>api.current?.rotate(-.4)} aria-label="Girar bancada para esquerda">←</button><button onClick={()=>api.current?.reset()}>Restaurar vista</button><button onClick={()=>api.current?.rotate(.4)} aria-label="Girar bancada para direita">→</button></div></div><p className="scene-caption">Modelo e materiais ilustrativos. Consulte amostras para o seu projeto.</p></div>;
}

